# Generated by Django 3.2.12 on 2022-02-27 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_kelompok'),
    ]

    operations = [
        migrations.AddField(
            model_name='kelompok',
            name='keterangan',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='kelompok',
            name='nama',
            field=models.CharField(max_length=50),
        ),
    ]
