# Generated by Django 3.2.12 on 2022-02-27 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20220227_2357'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Buku',
        ),
        migrations.DeleteModel(
            name='Kelompok',
        ),
    ]
