# Generated by Django 3.2.12 on 2022-03-03 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_remove_buku_jumlah_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pinjam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=50)),
                ('nama', models.CharField(max_length=50)),
                ('kelas', models.CharField(max_length=50)),
                ('tanggal', models.DateField(max_length=40)),
            ],
        ),
    ]
