# Generated by Django 3.2.12 on 2022-03-04 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_pengembalian'),
    ]

    operations = [
        migrations.AddField(
            model_name='pinjam',
            name='t_pengembalian',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
