# Generated by Django 3.2.12 on 2022-03-04 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_pinjam_t_pengembalian'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pinjam',
            name='t_pengembalian',
            field=models.DateField(max_length=50, null=True),
        ),
    ]
