# Generated by Django 3.2.12 on 2022-03-05 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='nama',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
