# Generated by Django 3.2.12 on 2022-03-06 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0015_notifikasi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifikasi',
            name='user_id',
        ),
        migrations.AddField(
            model_name='notifikasi',
            name='nama',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
