# Generated by Django 3.2.12 on 2022-03-06 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0016_auto_20220306_2006'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notifikasi',
        ),
    ]
