# Generated by Django 3.2.12 on 2022-03-07 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0018_user_kelas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='kelas',
        ),
    ]
