# Generated by Django 3.2.12 on 2022-03-07 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0019_remove_user_kelas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kelas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kls', models.CharField(max_length=50)),
            ],
        ),
    ]
