# Generated by Django 3.2.12 on 2022-03-07 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0020_kelas'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='kelas_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.kelas'),
        ),
    ]
