# Generated by Django 3.2.12 on 2022-03-08 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0021_user_kelas_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='buku',
            name='keterangan',
            field=models.TextField(null=True),
        ),
    ]
