# Generated by Django 3.2.12 on 2022-03-16 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0022_buku_keterangan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pengunjung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=60)),
                ('kls', models.CharField(max_length=70)),
                ('tanggal', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
