# Generated by Django 3.2.12 on 2022-03-20 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0024_user_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
